///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestGames_TestSuites
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestGames_TestSuitesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("607b305c-4e0e-49bd-97d3-4373163bab23")]
    public partial class TestGames_TestSuitesRepository : RepoGenBaseFolder
    {
        static TestGames_TestSuitesRepository instance = new TestGames_TestSuitesRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestGames_TestSuitesRepository element repository.
        /// </summary>
        [RepositoryFolder("607b305c-4e0e-49bd-97d3-4373163bab23")]
        public static TestGames_TestSuitesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestGames_TestSuitesRepository() 
            : base("TestGames_TestSuitesRepository", "/", null, 0, false, "607b305c-4e0e-49bd-97d3-4373163bab23", ".\\RepositoryImages\\TestGames_TestSuitesRepository607b305c.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("607b305c-4e0e-49bd-97d3-4373163bab23")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class TestGames_TestSuitesRepositoryFolders
    {
    }
#pragma warning restore 0436
}